#!/usr/bin/env bash

# change this variable to the theme you prefer
theme="~/.local/share/rofi/themes/windows/windows11-grid-dark"

rofi \
    -show drun \
    -terminal $term \
    -kb-cancel Escape \
    -theme $theme
