#!/usr/bin/env bash

launcher="~/.local/share/rofi/themes/catppuccin/basic/launcher"
term="kitty"

rofi \
    -show {drun,run,window} \
    -terminal $term \
	-kb-cancel Escape \
    -theme $launcher
